/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FarmaciaPurplePharma;

import Clases.*;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author Lithium582
 */
public class Principal extends javax.swing.JFrame {

    private Farmacia farma;
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
        
        farma = new Farmacia("UCUPharma","Avenida SiempreViva 582","666-333-666");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmCargaDeArchivo = new javax.swing.JMenu();
        jmCargarArticulos = new javax.swing.JMenuItem();
        jmCargarStock = new javax.swing.JMenuItem();
        jmArticulos = new javax.swing.JMenu();
        jmNuevoArticulo = new javax.swing.JMenuItem();
        jmListarTodosArticulos = new javax.swing.JMenuItem();
        jmBuscarArticulo = new javax.swing.JMenu();
        jmBuscarArticuloXCantidad = new javax.swing.JMenuItem();
        jmBusquedaGenerica = new javax.swing.JMenuItem();
        jmEliminarArticulo = new javax.swing.JMenuItem();
        jmMovimientos = new javax.swing.JMenu();
        jmNuevaVenta = new javax.swing.JMenuItem();
        jmDevolverVenta = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmListarTodasVentas = new javax.swing.JMenuItem();
        jmReportesPorFecha = new javax.swing.JMenuItem();
        jmReportesGenericos = new javax.swing.JMenuItem();
        jmAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PurplePharma Principal");
        setBackground(new java.awt.Color(0, 0, 0));

        jmCargaDeArchivo.setText("Carga de Archivos");

        jmCargarArticulos.setText("Cargar Artículos");
        jmCargarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargarArticulosActionPerformed(evt);
            }
        });
        jmCargaDeArchivo.add(jmCargarArticulos);

        jmCargarStock.setText("Cargar Stock");
        jmCargarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargarStockActionPerformed(evt);
            }
        });
        jmCargaDeArchivo.add(jmCargarStock);

        jMenuBar1.add(jmCargaDeArchivo);

        jmArticulos.setText("Artículos");

        jmNuevoArticulo.setText("Nuevo");
        jmNuevoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoArticuloActionPerformed(evt);
            }
        });
        jmArticulos.add(jmNuevoArticulo);

        jmListarTodosArticulos.setText("Listar Todos");
        jmArticulos.add(jmListarTodosArticulos);

        jmBuscarArticulo.setText("Buscar");

        jmBuscarArticuloXCantidad.setText("Cantidad de Artículos");
        jmBuscarArticulo.add(jmBuscarArticuloXCantidad);

        jmBusquedaGenerica.setText("Búsqueda Genérica");
        jmBuscarArticulo.add(jmBusquedaGenerica);

        jmArticulos.add(jmBuscarArticulo);

        jmEliminarArticulo.setText("Eliminar");
        jmArticulos.add(jmEliminarArticulo);

        jMenuBar1.add(jmArticulos);

        jmMovimientos.setText("Movimientos");

        jmNuevaVenta.setText("Nueva Venta");
        jmMovimientos.add(jmNuevaVenta);

        jmDevolverVenta.setText("Devolver Venta");
        jmMovimientos.add(jmDevolverVenta);

        jmReportes.setText("Reportes");

        jmListarTodasVentas.setText("Listar Todas");
        jmReportes.add(jmListarTodasVentas);

        jmReportesPorFecha.setText("Reportes por Fecha");
        jmReportes.add(jmReportesPorFecha);

        jmReportesGenericos.setText("Reportes Genéricos");
        jmReportes.add(jmReportesGenericos);

        jmMovimientos.add(jmReportes);

        jMenuBar1.add(jmMovimientos);

        jmAcercaDe.setText("Acerca De");
        jMenuBar1.add(jmAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCargarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargarArticulosActionPerformed

        ////Cerrar el form
        //this.dispose();
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        
        /*
        ERROR_MESSAGE
        INFORMATION_MESSAGE
        WARNING_MESSAGE
        QUESTION_MESSAGE
        PLAIN_MESSAGE 
        */
        
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String direccionArchivo = selectedFile.getAbsolutePath();
            Boolean b = farma.cargarArticulos(direccionArchivo);
            
            if (b){
                JOptionPane.showMessageDialog(null, "Archivo cargado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jmCargarArticulosActionPerformed

    private void jmCargarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargarStockActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String direccionArchivo = selectedFile.getAbsolutePath();
            Boolean b = farma.cargarStock(direccionArchivo);
            
            if (b){
                JOptionPane.showMessageDialog(null, "Archivo cargado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jmCargarStockActionPerformed

    private void jmNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoArticuloActionPerformed

        
        NuevoArticulo a = new NuevoArticulo();
        a.show();
    }//GEN-LAST:event_jmNuevoArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAcercaDe;
    private javax.swing.JMenu jmArticulos;
    private javax.swing.JMenu jmBuscarArticulo;
    private javax.swing.JMenuItem jmBuscarArticuloXCantidad;
    private javax.swing.JMenuItem jmBusquedaGenerica;
    private javax.swing.JMenu jmCargaDeArchivo;
    private javax.swing.JMenuItem jmCargarArticulos;
    private javax.swing.JMenuItem jmCargarStock;
    private javax.swing.JMenuItem jmDevolverVenta;
    private javax.swing.JMenuItem jmEliminarArticulo;
    private javax.swing.JMenuItem jmListarTodasVentas;
    private javax.swing.JMenuItem jmListarTodosArticulos;
    private javax.swing.JMenu jmMovimientos;
    private javax.swing.JMenuItem jmNuevaVenta;
    private javax.swing.JMenuItem jmNuevoArticulo;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmReportesGenericos;
    private javax.swing.JMenuItem jmReportesPorFecha;
    // End of variables declaration//GEN-END:variables

}
